apiVersion: v1
kind: Pod
metadata:
  name: legolas
  labels:
    name: legolas
    version: v1
spec:
  containers:
    - image: eu.gcr.io/dogwood-mission-261918/legolas:1.0
      name: legolas
      env:
        - name: "ENVIRONMENT"
          value: "PROD"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/credentials"
  volumes:
  - name: secret-volume
    secret:
      secretName: credentials-prod


